/**
 * 🎨 REACT COMPONENTS - Video Player UI Component Library
 * 
 * ===============================================================================
 * 📋 PURPOSE: Comprehensive UI component library for video player functionality
 * 🏗️ ARCHITECTURE: ShadCN UI foundation + Modular component system + Tailwind CSS
 * 🔗 RELATIONSHIPS: components → hooks → core → utilities
 * ===============================================================================
 * 
 * 🧩 COMPONENT CATEGORIES:
 * ├── 🎨 ShadCN UI Components - Foundation design system
 * │   ├── 🔘 Button, Card, Dialog, Input, Select, etc.
 * │   ├── 🎯 DO NOT MODIFY - Generated by ShadCN CLI
 * │   └── 🔗 Used by: All custom components, consistent theming
 * │
 * ├── 🎬 Core Player Components - Essential video player UI
 * │   ├── 📺 VideoPlayer, PlayerContainer, VideoElement
 * │   ├── 🛡️ ErrorBoundary, LoadingIndicator
 * │   └── 🔗 Used in: Main app, video pages, demos
 * │
 * ├── 🎮 Control Components - User interaction controls
 * │   ├── ▶️ PlayButton, ProgressBar, VolumeControl
 * │   ├── ⚙️ QualitySelector, SettingsMenu, FullscreenButton
 * │   └── 🔗 Used in: PlayerContainer, ControlBar, CustomControls
 * │
 * ├── 🎭 Overlay Components - Player overlay elements
 * │   ├── 🎯 CenterOverlay, LoadingOverlay, ErrorOverlay
 * │   ├── 👆 GestureFeedback, BufferIndicator
 * │   └── 🔗 Used in: PlayerContainer, OverlayManager
 * │
 * ├── 🖼️ Thumbnail Components - Preview and navigation
 * │   ├── 🎬 ThumbnailPreview, TimelineThumbnails
 * │   ├── 📑 ChapterThumbnails, SpriteRenderer
 * │   └── 🔗 Used in: ProgressBar, ChapterNavigation
 * │
 * ├── 📊 Analytics Components - Performance and metrics UI
 * │   ├── 📈 MetricsDisplay, AnalyticsPanel
 * │   ├── ⚡ PerformanceMonitor, HeatmapDisplay
 * │   └── 🔗 Used in: DeveloperTools, AdminDashboard
 * │
 * └── ⚙️ Configuration Components - Player setup and customization
 *     ├── 🛠️ PlayerConfigurator, ThemeSelector
 *     ├── 🧩 PluginManager, PresetManager
 *     └── 🔗 Used in: SettingsPage, AdminPanel, SetupWizard
 * 
 * 🎯 INTEGRATION EXAMPLES:
 * ```typescript
 * // Core player usage
 * import { VideoPlayer, PlayerContainer } from '@/components'
 * 
 * // Control components
 * import { PlayButton, VolumeControl } from '@/components/controls'
 * 
 * // ShadCN UI components
 * import { Button, Card, Dialog } from '@/components/ui'
 * 
 * // Complete component library
 * import * as Components from '@/components'
 * ```
 */

// 🎨 ShadCN UI Components - Foundation Design System (DO NOT MODIFY)
export * from './ui'                                            // 🔘 Design system - used by: all custom components, consistent theming

// 🎬 Core Player Components - Essential Video Player UI
export * from './player'                                        // 📺 Player core - used in: main app, video pages, demos

// 🎮 Player Control Components - User Interaction Controls
export * from './controls'                                      // ▶️ User controls - used in: PlayerContainer, ControlBar, CustomControls

// 🎭 Player Overlay Components - Overlay Elements
export * from './overlays'                                      // 🎯 Player overlays - used in: PlayerContainer, OverlayManager

// 🖼️ Thumbnail Components - Preview and Navigation
export * from './thumbnails'                                    // 🎬 Thumbnail system - used in: ProgressBar, ChapterNavigation

// 📊 Analytics UI Components - Performance and Metrics
export * from './analytics'                                     // 📈 Analytics UI - used in: DeveloperTools, AdminDashboard

// ⚙️ Configuration Components - Player Setup and Customization
export * from './configuration'                                 // 🛠️ Player config - used in: SettingsPage, AdminPanel, SetupWizard
